; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:wiscore_rak4631]
platform = nordicnrf52
board = wiscore_rak4631
framework = arduino
; debug_tool = jlink
build_flags =
	-D MY_DEBUG=1
	-D API_DEBUG=0
	-D LIB_DEBUG=0
	-D SW_VERSION_1=1
	-D SW_VERSION_2=1
	-D SW_VERSION_3=9
	-D FREQ_VERSION=H
	-D HIGH_FREQ=1
	-D FAKE_GPS=0	 ; 1 Enable to get a fake GPS position if no location fix could be obtained
	-D NO_EPD=1       ; 1 to enable EPD
lib_deps = 
	beegee-tokyo/WisBlock-API-V2
	beegee-tokyo/nRF52_OLED
	beegee-tokyo/RAK14000_EPD
	sparkfun/SparkFun u-blox GNSS Arduino Library 
extra_scripts = 
	pre:rename.py
	create_uf2.py

[env:wiscore_rak4631_l]
platform = nordicnrf52
board = wiscore_rak4631
framework = arduino
; debug_tool = jlink
build_flags =
	-D MY_DEBUG=1
	-D API_DEBUG=0
	-D LIB_DEBUG=0
	-D SW_VERSION_1=1
	-D SW_VERSION_2=1
	-D SW_VERSION_3=9
	-D FREQ_VERSION=L
	-D FAKE_GPS=0	 ; 1 Enable to get a fake GPS position if no location fix could be obtained
	-D NO_EPD=1       ; 1 to enable EPD
lib_deps = 
	beegee-tokyo/WisBlock-API-V2
	beegee-tokyo/nRF52_OLED
	beegee-tokyo/RAK14000_EPD
	sparkfun/SparkFun u-blox GNSS Arduino Library 
extra_scripts = 
	pre:rename.py
	create_uf2.py
