[platformio]
default_envs = 
	rak4631
	rak4631_l
	rak3401
	rak3312
boards_dir = rakwireless/boards

[common]
build_flags =
	-D MY_DEBUG=1
	-D API_DEBUG=0
	-D LIB_DEBUG=0
	-D SW_VERSION_1=3
	-D SW_VERSION_2=0
	-D SW_VERSION_3=0
	-D FAKE_GPS=0	 ; 1 Enable to get a fake GPS position if no location fix could be obtained
	-D NO_EPD=1       ; 1 to enable EPD
lib_deps = 
	beegee-tokyo/WisBlock-API-V2
	beegee-tokyo/nRF52_OLED
	sparkfun/SparkFun u-blox GNSS Arduino Library
	mikalhart/TinyGPSPlus
	beegee-tokyo/RAK13800-W5100S
extra_scripts = 
	pre:rename.py
	create_uf2.py

[env:rak4631]
platform = nordicnrf52
board = rak4630
framework = arduino
; debug_tool = jlink
build_src_filter = ${env.build_src_filter}+<../rakwireless/variants/rak4630>
build_flags =
	${common.build_flags}
	-D FREQ_VERSION=H
	-D HIGH_FREQ=1
	-D CORE_VERSION=RAK4631
	-D SUPPORTS_RAK14000=1
	-D SUPPORTS_RAK13800=1
	-I rakwireless/variants/rak4630
lib_deps = 
	${common.lib_deps}
	beegee-tokyo/RAK14000_EPD
extra_scripts = 
	${common.extra_scripts}

[env:rak4631_l]
platform = nordicnrf52
board = rak4630
framework = arduino
; debug_tool = jlink
build_src_filter = ${env.build_src_filter}+<../rakwireless/variants/rak4630>
build_flags =
	${common.build_flags}
	-D FREQ_VERSION=L
	-D CORE_VERSION=RAK4631
	-D SUPPORTS_RAK14000=1
	-D SUPPORTS_RAK13800=1
	-I rakwireless/variants/rak4630
lib_deps = 
	${common.lib_deps}
	beegee-tokyo/RAK14000_EPD
extra_scripts = 
	${common.extra_scripts}

[env:rak3401]
platform = nordicnrf52
board = rak4630
framework = arduino
; debug_tool = jlink
build_src_filter = ${env.build_src_filter}+<../rakwireless/variants/rak4630>
build_flags =
	${common.build_flags}
	-D FREQ_VERSION=1w
	-D HIGH_FREQ=1
	-D _VARIANT_RAK3400_=1
	-D CORE_VERSION=RAK3401
	-I rakwireless/variants/rak4630
lib_deps = 
	${common.lib_deps}
extra_scripts = 
	${common.extra_scripts}

[env:rak3312]
platform = platformio/espressif32
board = rak3112
framework = arduino
upload_protocol = esptool
upload_speed = 921600
monitor_speed = 115200
board_build.filesystem = littlefs
board_upload.after_reset = hard_reset
build_src_filter = ${env.build_src_filter}+<../rakwireless/variants/rak3112>
build_flags =
	${common.build_flags}
	-D FREQ_VERSION=H
	-D HIGH_FREQ=1
	-D CORE_VERSION=RAK3312
	-D _VARIANT_RAK3112_=1
	-D CORE_VERSION=RAK3312
	-D SUPPORTS_RAK13800=1
	-I rakwireless/variants/rak3112
lib_deps = 
	${common.lib_deps}
extra_scripts = 
	${common.extra_scripts}
	copy_esp32.py
